// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\Alexander\GolandProjects\Tech_task\internal\repository\wallets\querier.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	wallets "tech_task/internal/repository/wallets"

	gomock "github.com/golang/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddAmount mocks base method.
func (m *MockQuerier) AddAmount(ctx context.Context, arg *wallets.AddAmountParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAmount", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAmount indicates an expected call of AddAmount.
func (mr *MockQuerierMockRecorder) AddAmount(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAmount", reflect.TypeOf((*MockQuerier)(nil).AddAmount), ctx, arg)
}

// CreateWalletOperation mocks base method.
func (m *MockQuerier) CreateWalletOperation(ctx context.Context, arg *wallets.CreateWalletOperationParams) (*wallets.RequestsHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWalletOperation", ctx, arg)
	ret0, _ := ret[0].(*wallets.RequestsHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWalletOperation indicates an expected call of CreateWalletOperation.
func (mr *MockQuerierMockRecorder) CreateWalletOperation(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWalletOperation", reflect.TypeOf((*MockQuerier)(nil).CreateWalletOperation), ctx, arg)
}

// GetWalletAmount mocks base method.
func (m *MockQuerier) GetWalletAmount(ctx context.Context, arg *wallets.GetWalletAmountParams) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletAmount", ctx, arg)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletAmount indicates an expected call of GetWalletAmount.
func (mr *MockQuerierMockRecorder) GetWalletAmount(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletAmount", reflect.TypeOf((*MockQuerier)(nil).GetWalletAmount), ctx, arg)
}

// SubtractAmountIfEnough mocks base method.
func (m *MockQuerier) SubtractAmountIfEnough(ctx context.Context, arg *wallets.SubtractAmountIfEnoughParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubtractAmountIfEnough", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubtractAmountIfEnough indicates an expected call of SubtractAmountIfEnough.
func (mr *MockQuerierMockRecorder) SubtractAmountIfEnough(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubtractAmountIfEnough", reflect.TypeOf((*MockQuerier)(nil).SubtractAmountIfEnough), ctx, arg)
}
