// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package wallets

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Wallet struct {
	Valletid      pgtype.UUID `db:"valletid" json:"valletid"`
	Operationtype string      `db:"operationtype" json:"operationtype"`
	Amount        int32       `db:"amount" json:"amount"`
}
