// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package wallets

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RequestsHistory struct {
	Operationtype string      `db:"operationtype" json:"operationtype"`
	WalletID      pgtype.UUID `db:"wallet_id" json:"wallet_id"`
	Amount        float32     `db:"amount" json:"amount"`
}

type Wallet struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Amount float32     `db:"amount" json:"amount"`
}
