// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package wallets

import (
	"context"
)

type Querier interface {
	CreateWalletOperation(ctx context.Context, arg *CreateWalletOperationParams) (*Wallet, error)
	GetWalletAmount(ctx context.Context, arg *GetWalletAmountParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
