// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package wallets

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAmount = `-- name: AddAmount :exec
UPDATE wallets
SET amount = amount + $2
WHERE id = $1
`

type AddAmountParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Amount float32     `db:"amount" json:"amount"`
}

func (q *Queries) AddAmount(ctx context.Context, arg *AddAmountParams) error {
	_, err := q.db.Exec(ctx, addAmount, arg.ID, arg.Amount)
	return err
}

const createWalletOperation = `-- name: CreateWalletOperation :one
INSERT INTO requests_history (operationType, amount, wallet_id)
VALUES ($1, $2, $3)
RETURNING operationtype, wallet_id, amount
`

type CreateWalletOperationParams struct {
	Operationtype string      `db:"operationtype" json:"operationtype"`
	Amount        float32     `db:"amount" json:"amount"`
	WalletID      pgtype.UUID `db:"wallet_id" json:"wallet_id"`
}

func (q *Queries) CreateWalletOperation(ctx context.Context, arg *CreateWalletOperationParams) (*RequestsHistory, error) {
	row := q.db.QueryRow(ctx, createWalletOperation, arg.Operationtype, arg.Amount, arg.WalletID)
	var i RequestsHistory
	err := row.Scan(&i.Operationtype, &i.WalletID, &i.Amount)
	return &i, err
}

const getWalletAmount = `-- name: GetWalletAmount :one
SELECT amount
FROM wallets
WHERE id = $1
`

type GetWalletAmountParams struct {
	ID pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) GetWalletAmount(ctx context.Context, arg *GetWalletAmountParams) (float32, error) {
	row := q.db.QueryRow(ctx, getWalletAmount, arg.ID)
	var amount float32
	err := row.Scan(&amount)
	return amount, err
}

const subtractAmountIfEnough = `-- name: SubtractAmountIfEnough :exec
UPDATE wallets
SET amount = amount - $2
WHERE id = $1 AND amount >= $2
`

type SubtractAmountIfEnoughParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Amount float32     `db:"amount" json:"amount"`
}

func (q *Queries) SubtractAmountIfEnough(ctx context.Context, arg *SubtractAmountIfEnoughParams) error {
	_, err := q.db.Exec(ctx, subtractAmountIfEnough, arg.ID, arg.Amount)
	return err
}

const updateWalletAmount = `-- name: UpdateWalletAmount :exec
UPDATE wallets
SET amount = $2
WHERE id = $1
`

type UpdateWalletAmountParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Amount float32     `db:"amount" json:"amount"`
}

func (q *Queries) UpdateWalletAmount(ctx context.Context, arg *UpdateWalletAmountParams) error {
	_, err := q.db.Exec(ctx, updateWalletAmount, arg.ID, arg.Amount)
	return err
}
