// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package wallets

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWalletOperation = `-- name: CreateWalletOperation :one
INSERT INTO wallets (operationType, amount)
VALUES ($1, $2)
RETURNING valletid, operationtype, amount
`

type CreateWalletOperationParams struct {
	Operationtype string `db:"operationtype" json:"operationtype"`
	Amount        int32  `db:"amount" json:"amount"`
}

func (q *Queries) CreateWalletOperation(ctx context.Context, arg *CreateWalletOperationParams) (*Wallet, error) {
	row := q.db.QueryRow(ctx, createWalletOperation, arg.Operationtype, arg.Amount)
	var i Wallet
	err := row.Scan(&i.Valletid, &i.Operationtype, &i.Amount)
	return &i, err
}

const getWalletAmount = `-- name: GetWalletAmount :one
SELECT amount
FROM wallets
WHERE valletId = $1
`

type GetWalletAmountParams struct {
	Valletid pgtype.UUID `db:"valletid" json:"valletid"`
}

func (q *Queries) GetWalletAmount(ctx context.Context, arg *GetWalletAmountParams) (int32, error) {
	row := q.db.QueryRow(ctx, getWalletAmount, arg.Valletid)
	var amount int32
	err := row.Scan(&amount)
	return amount, err
}
