// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\Alexander\GolandProjects\Tech_task\internal\usecase\wallets\usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIUseCase is a mock of IUseCase interface.
type MockIUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIUseCaseMockRecorder
}

// MockIUseCaseMockRecorder is the mock recorder for MockIUseCase.
type MockIUseCaseMockRecorder struct {
	mock *MockIUseCase
}

// NewMockIUseCase creates a new mock instance.
func NewMockIUseCase(ctrl *gomock.Controller) *MockIUseCase {
	mock := &MockIUseCase{ctrl: ctrl}
	mock.recorder = &MockIUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUseCase) EXPECT() *MockIUseCaseMockRecorder {
	return m.recorder
}

// CreateWalletOperation mocks base method.
func (m *MockIUseCase) CreateWalletOperation(ctx context.Context, walletID uuid.UUID, operationType string, walletAmount float32) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWalletOperation", ctx, walletID, operationType, walletAmount)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWalletOperation indicates an expected call of CreateWalletOperation.
func (mr *MockIUseCaseMockRecorder) CreateWalletOperation(ctx, walletID, operationType, walletAmount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWalletOperation", reflect.TypeOf((*MockIUseCase)(nil).CreateWalletOperation), ctx, walletID, operationType, walletAmount)
}

// GetWalletAmount mocks base method.
func (m *MockIUseCase) GetWalletAmount(ctx context.Context, walletID uuid.UUID) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletAmount", ctx, walletID)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletAmount indicates an expected call of GetWalletAmount.
func (mr *MockIUseCaseMockRecorder) GetWalletAmount(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletAmount", reflect.TypeOf((*MockIUseCase)(nil).GetWalletAmount), ctx, walletID)
}
